apiVersion: v1
kind: Service
metadata:
  name: ftp
  annotations:
    metallb.universe.tf/address-pool: default # this is name of config in metallb
    metallb.universe.tf/allow-shared-ip: "web-server-svc" # https://metallb.universe.tf/usage/#ip-address-sharing
spec:
  selector:
    app: ftp
  ports:
  - protocol: TCP
    port: 21
    targetPort: 21
    # name: https
    # nodePort: 30099
  externalTrafficPolicy: Cluster # this is default so not spec in other pods
  type: LoadBalancer
  # loadBalancerIP: 127.0.0.1 #192.168.1.239 #GiveIPAddress
  # clusterIP: None
---
apiVersion: apps/v1
kind: Deployment #StatefulSet #
metadata:
  name: ftp
  labels:
    app: ftp
spec:
  replicas: 1
  # serviceName: "ftp" # for statefull
  selector:
    matchLabels:
      app: ftp
  template:
    metadata:
      labels:
        app: ftp
    spec:
      containers:
      - name: ftp
        image: img_ftp #ftp:alpine
        imagePullPolicy: Never #IfNotPresent
        env:
        - name: INFLUX_URL
          value: influx
        ports:
        - containerPort: 21
