apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: "web-server-svc"
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: port
      # nodePort: 30033
  selector:
    app: grafana
    tier: frontend
  type: LoadBalancer
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: wp-pv-claim
#   labels:
#     app: wordpress
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grafana
        tier: frontend
    spec:
      containers:
      - image: img_grafana #wordpress:fpm-alpine
        imagePullPolicy: Never #IfNotPresent 
        name: grafana
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
            # https://stackoverflow.com/questions/59958274/unable-to-connect-to-the-server-net-http-tls-handshake-timeout
            # https://medium.com/@betz.mark/understanding-resource-limits-in-kubernetes-cpu-time-9eff74d3161b
            #
            # The unit suffix m stands for “thousandth of a core,” so this resources object specifies that 
            # the container process needs 50/1000 of a core (5%) and is allowed to use at most 100/1000 of a core (10%).
            # Likewise 2000m would be two full cores, which can also be specified as 2 or 2.0.
            # Let’s create a pod with just a request for cpu and see how this is configured at the docker and cgroup levels

        env:
        - name: INFLUX_URL
          value: influx
        # - name: WORDPRESS_DB_HOST
        #   value: wordpress-mysql
        # - name: WORDPRESS_DB_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: mysql-pass
        #       key: password
        # - name: WORDPRESS_DB_NAME
        #   valueFrom:
        #     configMapKeyRef:
        #       name: db-configmap
        #       key: db_name
        # - name: WORDPRESS_DB_USER
        #   value: root
        ports:
        - containerPort: 3000
          name: grafana
        # volumeMounts:
        # - name: wordpress-persistent-storage
        #   mountPath: /var/www/html
      # volumes:
      # - name: wordpress-persistent-storage
        # persistentVolumeClaim:
        #   claimName: wp-pv-claim
        livenessProbe:
          httpGet:
            path: /api/health
            port: port
          failureThreshold: 2
          initialDelaySeconds: 20
