apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      # nodePort: 30033
  selector:
    app: grafana
    tier: frontend
  type: LoadBalancer
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: wp-pv-claim
#   labels:
#     app: wordpress
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grafana
        tier: frontend
    spec:
      containers:
      - image: img_grafana #wordpress:fpm-alpine
        imagePullPolicy: Never #IfNotPresent 
        name: grafana
        # env:
        # - name: WORDPRESS_DB_HOST
        #   value: wordpress-mysql
        # - name: WORDPRESS_DB_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: mysql-pass
        #       key: password
        # - name: WORDPRESS_DB_NAME
        #   valueFrom:
        #     configMapKeyRef:
        #       name: db-configmap
        #       key: db_name
        # - name: WORDPRESS_DB_USER
        #   value: root
        ports:
        - containerPort: 3000
          name: grafana
        # volumeMounts:
        # - name: wordpress-persistent-storage
        #   mountPath: /var/www/html
      # volumes:
      # - name: wordpress-persistent-storage
        # persistentVolumeClaim:
        #   claimName: wp-pv-claim
