apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
spec:
  ports:
    - port: 3306
      # targetPort: 3306
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: Secret
metadata:
    name: mysql-pass
type: Opaque
data:
    password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-configmap
data:
  db_name: db # name of the to connect service
  db_user: new
  db_pass: pass
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: mysql-pv-vol
#   labels:
#     type: local
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 500Mi #1Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/mnt/sql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi #20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
      - image: img_mysql #mysql:5.6
        name: mysql
        imagePullPolicy: Never #IfNotPresent 
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: MYSQL_DATABASE
          valueFrom: 
            configMapKeyRef:
              name: db-configmap
              key: db_name
        - name: MYSQL_USER
          valueFrom: 
            configMapKeyRef:
              name: db-configmap
              key: db_user
        - name: MYSQL_PASSWORD
          valueFrom: 
            configMapKeyRef:
              name: db-configmap
              key: db_pass
        - name: INFLUX_URL
          value: influx
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
