apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        # ports:
        # - containerPort: 8080
        #
        volumeMounts:
          - name: conf 
            mountPath: /etc/nginx/nginx.conf  
            subPath: nginx.conf
            # readOnly: true
      volumes:  # those volumes may be not here. Now these volumes mounts above in container
        - name: conf
          configMap:
            name: nginx-config-file
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-file
data:
  nginx.conf: |
    events {
        worker_connections  1024;
    }

    http {
        # The identifier Backend is internal to nginx, and used to name this specific upstream
        upstream Backend {
        # hello is the internal DNS name used by the backend Service inside Kubernetes
            server pma;
        }
        upstream WP {
        # hello is the internal DNS name used by the backend Service inside Kubernetes
            server wordpress;
        }
        
        server {
            listen 80;

            location / {
                include fastcgi_params;
                fastcgi_pass WP;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            }
        
            location /phpmyadmin {
                # The following statement will proxy traffic to the upstream named Backend
                proxy_pass http://Backend;
            }
            location ^~ /wordpress {
                include fastcgi_params;
                fastcgi_pass WP;
                # fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            }
        }
    }
