apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  annotations:
    metallb.universe.tf/address-pool: default # this is name of config in metallb
    metallb.universe.tf/allow-shared-ip: "web-server-svc" # https://metallb.universe.tf/usage/#ip-address-sharing
spec:
  selector:
    app: nginx
  ports:
  - protocol: "TCP"
    port: 2001
    targetPort: 80
    # nodePort: 30099
  externalTrafficPolicy: Cluster # this is default so not spec in other pods
  type: LoadBalancer
  # loadBalancerIP: 127.0.0.1 #192.168.1.239 #GiveIPAddress
  # clusterIP: None
---
apiVersion: apps/v1
kind: Deployment #StatefulSet #
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 3
  # serviceName: "nginx" # for statefull
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: img_nginx #nginx:alpine 
        imagePullPolicy: Never #IfNotPresent 
        env:
        - name: INFLUX_URL
          value: influx
         ports:
         - containerPort: 80
