apiVersion: v1
kind: Service
metadata:
  name: pma
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: "web-server-svc"
  labels:
    app: wordpress
spec:
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 5000
      # nodePort: 30000
      name: http
      targetPort: 80
  selector:
    app: wordpress
    tier: pma
    # clusterIP: None
  # loadBalancerIP: 127.0.0.1 #192.168.1.239 #GiveIPAddress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pma
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      tier: pma
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: pma
    spec:
      containers:
      - image: img_pma_orig #phpmyadmin:fpm-alpine #
        name: pma
        imagePullPolicy: Never #IfNotPresent 
        env:
        - name: INFLUX_URL
          value: influx
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: PMA_HOST 
          value: mysql
          # valueFrom: 
          #   configMapKeyRef:
          #     name: pma-configmap
          #     key: database_url
        ports:
        - containerPort: 80
          name: pmaa
        livenessProbe:
          httpGet:
            # path: / this is default
            port: http
          failureThreshold: 2
          initialDelaySeconds: 5
          periodSeconds: 10
