apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: "web-server-svc"
spec:
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 80
      name: http
      # nodePort: 30033
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: wp-pv-claim
#   labels:
#     app: wordpress
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: img_wp #wordpress:fpm-alpine
        imagePullPolicy: Never #IfNotPresent 
        name: wordpress
        env:
        - name: INFLUX_URL
          value: influx
        - name: EXTERNAL
          value: 45.138.25.104
        - name: WORDPRESS_DB_HOST
          value: mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: WORDPRESS_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-configmap
              key: db_name
        - name: WORDPRESS_DB_USER
          value: root
        ports:
        - containerPort: 80
          name: wordpress
        livenessProbe:
          httpGet:
            # path: / this is default
            port: http
          failureThreshold: 2
          initialDelaySeconds: 5
          periodSeconds: 10
        # volumeMounts:
        # - name: wordpress-persistent-storage
        #   mountPath: /var/www/html
      # volumes:
      # - name: wordpress-persistent-storage
        # persistentVolumeClaim:
        #   claimName: wp-pv-claim
