{
 "title": "phpmyadmin",
 "time": { "from": "2021-11-24T13:47:12.857Z", "to": "2021-11-24T22:09:55.911Z" },
 "panels": [
  {
   "title": "net",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"bytes_recv\") AS \"bytes_recv\" FROM \"net\" WHERE host =~ /pma*/ AND $timeFilter GROUP BY time(10s), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "bytes_recv" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pma-69d97fc685-6l7sj" }
     ]
    },
    {
     "alias": "$m  $col $tag_host",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"bytes_sent\") AS \"bytes_sent\"  FROM \"net\" WHERE host =~ /pma*/ AND $timeFilter GROUP BY time(10s), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "select tag value" }
     ]
    }
   ]
  },
  {
   "title": "mem",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT mean(\"active\") AS \"active\" FROM \"mem\" WHERE host =~ /pma*/ AND $timeFilter GROUP BY time(10s), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pma-69d97fc685-4d4m4" }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"usage_system\") AS \"system\" FROM \"cpu\" WHERE host =~ /pma*/ AND $timeFilter GROUP BY time(10s), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pma-69d97fc685-4d4m4" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"usage_user\") AS \"user\" FROM \"cpu\" WHERE host =~ /pma*/ AND $timeFilter GROUP BY time(10s), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "" }
     ]
    }
   ]
  }
 ]
}