# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: influxDB
    orgId: 1

# list of datasources to insert/update depending
# what's available in the database
datasources:
    - name: influxdb
      type: influxdb
      access: proxy
      database: telegraf
      # user: grafana
      url: http://influx:8086
      # secureJsonData:
      #   password: grafana
