#!/bin/bash
docker rm -f $(docker ps -aq) || 0
docker rmi $(docker images -aq)
set -xe
docker build -t base .
# docker run -p 8080:80 -dt base 
# docker exec -it $(docker ps -q) /bin/sh

# docker inspect $(docker ps -aq) | grep '"IPAddress"' | head -n 1
# https://stackoverflow.com/questions/41322541/rebuild-docker-container-on-file-changes
